name: linting

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: configure conda and install code
          # Test against latest releases of each code in the dependency chain
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet \
            --file=requirements.txt
          python -m pip install --no-deps -e .
          conda install -y -q \
            flake8 \
            pytest \
            pytest-xdist \
            pytest-cov \
            pip \
            setuptools \
            "setuptools_scm>=7,<8" \
            python-build \
            flake8-pyproject
          python -m pip install --no-build-isolation --no-deps -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 dsps
