name: Test for Warnings

on:
  workflow_dispatch: null
  schedule:
    # Runs "First of every month at 3:15am Central"
    - cron: '15 8 1 * *'

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: configure conda and install code
          # Test against latest releases of each code in the dependency chain
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          mamba install --quiet \
            --file=requirements.txt
          python -m pip install --no-deps -e .
          mamba install -y -q \
            flake8 \
            pytest \
            pytest-xdist \
            pytest-cov \
            pip \
            setuptools \
            "setuptools_scm>=7,<8" \
            python-build \
            flake8-pyproject
          python -m pip install --no-build-isolation --no-deps -e .

      - name: test that no warnings are raised
        shell: bash -l {0}
        run: |
          export PYTHONWARNINGS=error
          pytest -v dsps --cov --cov-report=xml
